create table customer(
  personid int,
  first_name varchar(255),
  last_name varchar(255)
);

CREATE USER IF NOT EXISTS KEVIN_HOE;

ALTER USER KEVIN_HOE SET EMAIL = 'khoe@rapid7.com';
ALTER USER KEVIN_HOE SET DISPLAY_NAME = KEVIN_HOE;
ALTER USER KEVIN_HOE SET LOGIN_NAME = 'khoe@rapid7.com';
ALTER USER KEVIN_HOE SET FIRST_NAME = 'KEVIN';
ALTER USER KEVIN_HOE SET LAST_NAME = 'HOE';
ALTER USER KEVIN_HOE SET DEFAULT_WAREHOUSE = 'SNOWFLAKE_WH';
ALTER USER KEVIN_HOE SET DEFAULT_NAMESPACE = 'KEVIN_HOE_SANDBOX';

CREATE SCHEMA 'SANDBOX_ENVIRONMENT.KEVIN_HOE_SANDBOX';
----------------------------------------------------------
--Roles for Individual Contributors
CREATE ROLE IF NOT EXISTS ROLE_KEVIN_HOE;
COMMENT ON ROLE ROLE_KEVIN_HOE IS 'Primary role assigned to KEVIN_HOE';
GRANT ROLE ROLE_KEVIN_HOE TO USER KEVIN_HOE;
